services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: mysql:latest
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"

volumes:
    mysql_data:
